### PR TITLE
Make Channel co-owned by Session and SessionWriter

### LINKED ISSUE #40: Heap use after free on shutdown
Integrated `BINLOG_INFO` logging into google benchmark based tests and receive the following on shutdown.

```==30054==ERROR: AddressSanitizer: heap-use-after-free on address 0x60600000d830 at pc 0x00000068fcc6 bp 0x7ffd6a8dda30 sp 0x7ffd6a8dda20
WRITE of size 1 at 0x60600000d830 thread T0
    #0 0x68fcc5 in std::__atomic_base<bool>::store(bool, std::memory_order) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/atomic_base.h:374:2
    #1 0x68fcc5 in std::__atomic_base<bool>::operator=(bool) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/atomic_base.h:267
    #2 0x68fa0d in std::atomic<bool>::operator=(bool) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/atomic:79:22
    #3 0x680c1d in binlog::SessionWriter::~SessionWriter() /Morgan-Stanley_binlog/20200306_0c86ccd/include/binlog/SessionWriter.hpp:135:22
    #4 0x7efc08019e08  (/lib64/libstdc++.so.6+0x5ce08)
    #5 0x7efc072faa68 in __run_exit_handlers (/lib64/libc.so.6+0x38a68)
    #6 0x7efc072faab4 in __GI_exit (/lib64/libc.so.6+0x38ab4)
    #7 0x7efc072e3c0b in __libc_start_main (/lib64/libc.so.6+0x21c0b)
    #8 0x512ea8 in _start (perf+0x512ea8)

0x60600000d830 is located 16 bytes inside of 56-byte region [0x60600000d820,0x60600000d858)
freed by thread T0 here:
    #0 0x6452e0 in operator delete(void*) (perf+0x6452e0)
    #1 0x687667 in __gnu_cxx::new_allocator<std::_List_node<binlog::Session::Channel> >::deallocate(std::_List_node<binlog::Session::Channel>*, unsigned long) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/ext/new_allocator.h:125:2
    #2 0x687614 in std::allocator_traits<std::allocator<std::_List_node<binlog::Session::Channel> > >::deallocate(std::allocator<std::_List_node<binlog::Session::Channel> >&, std::_List_node<binlog::Session::Channel>*, unsigned long) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/alloc_traits.h:462:13
    #3 0x68621e in std::_List_base<binlog::Session::Channel, std::allocator<binlog::Session::Channel> >::_M_put_node(std::_List_node<binlog::Session::Channel>*) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_list.h:454:9
    #4 0x685f23 in std::_List_base<binlog::Session::Channel, std::allocator<binlog::Session::Channel> >::_M_clear() /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/list.tcc:81:4
    #5 0x685be1 in std::_List_base<binlog::Session::Channel, std::allocator<binlog::Session::Channel> >::~_List_base() /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_list.h:507:9
    #6 0x681624 in std::list<binlog::Session::Channel, std::allocator<binlog::Session::Channel> >::~list() /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_list.h:835:23
    #7 0x680e18 in binlog::Session::~Session() /Morgan-Stanley_binlog/20200306_0c86ccd/include/binlog/Session.hpp:46:7
    #8 0x7efc072faa68 in __run_exit_handlers (/lib64/libc.so.6+0x38a68)

previously allocated by thread T0 here:
    #0 0x644350 in operator new(unsigned long) (perf+0x644350)
    #1 0x68a4cc in __gnu_cxx::new_allocator<std::_List_node<binlog::Session::Channel> >::allocate(unsigned long, void const*) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/ext/new_allocator.h:111:27
    #2 0x68a430 in std::allocator_traits<std::allocator<std::_List_node<binlog::Session::Channel> > >::allocate(std::allocator<std::_List_node<binlog::Session::Channel> >&, unsigned long) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/alloc_traits.h:436:20
    #3 0x689ee6 in std::_List_base<binlog::Session::Channel, std::allocator<binlog::Session::Channel> >::_M_get_node() /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_list.h:450:16
    #4 0x6899b3 in std::_List_node<binlog::Session::Channel>* std::list<binlog::Session::Channel, std::allocator<binlog::Session::Channel> >::_M_create_node<binlog::Session&, unsigned long&, binlog::WriterProp>(binlog::Session&, unsigned long&, binlog::WriterProp&&) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_list.h:642:21
    #5 0x689393 in void std::list<binlog::Session::Channel, std::allocator<binlog::Session::Channel> >::_M_insert<binlog::Session&, unsigned long&, binlog::WriterProp>(std::_List_iterator<binlog::Session::Channel>, binlog::Session&, unsigned long&, binlog::WriterProp&&) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_list.h:1903:18
    #6 0x688bb6 in binlog::Session::Channel& std::list<binlog::Session::Channel, std::allocator<binlog::Session::Channel> >::emplace_back<binlog::Session&, unsigned long&, binlog::WriterProp>(binlog::Session&, unsigned long&, binlog::WriterProp&&) /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_list.h:1235:10
    #7 0x687f84 in binlog::Session::createChannel(unsigned long, binlog::WriterProp) /Morgan-Stanley_binlog/20200306_0c86ccd/include/binlog/Session.hpp:241:13
    #8 0x699e3c in binlog::SessionWriter::replaceChannel(unsigned long) /Morgan-Stanley_binlog/20200306_0c86ccd/include/binlog/SessionWriter.hpp:203:46
    #9 0x738732 in bool binlog::SessionWriter::addEvent<std::string const&, unsigned long, unsigned long, std::basic_string_view<char, std::char_traits<char> >, unsigned long, unsigned int>(unsigned long, unsigned long, std::string const&, unsigned long&&, unsigned long&&, std::basic_string_view<char, std::char_traits<char> >&&, unsigned long&&, unsigned int&&) /Morgan-Stanley_binlog/20200306_0c86ccd/include/binlog/SessionWriter.hpp:179:5
    #10 0x73597d in void binlog::detail::addEventIgnoreFirst<binlog::SessionWriter, char const (&) [104], std::string const&, unsigned long, unsigned long, std::basic_string_view<char, std::char_traits<char> >, unsigned long, unsigned int>(binlog::SessionWriter&, unsigned long, unsigned long, char const (&) [104], std::string const&, unsigned long&&, unsigned long&&, std::basic_string_view<char, std::char_traits<char> >&&, unsigned long&&, unsigned int&&) /Morgan-Stanley_binlog/20200306_0c86ccd/include/binlog/create_source_and_event.hpp:95:10
    #11
	
	snip
	
    #24 0x7efc072e3c04 in __libc_start_main (/lib64/libc.so.6+0x21c04)

SUMMARY: AddressSanitizer: heap-use-after-free /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/atomic_base.h:374:2 in std::__atomic_base<bool>::store(bool, std::memory_order)
Shadow bytes around the buggy address:
  0x0c0c7fff9ab0: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
  0x0c0c7fff9ac0: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c0c7fff9ad0: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
  0x0c0c7fff9ae0: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
  0x0c0c7fff9af0: fd fd fd fa fa fa fa fa fd fd fd fd fd fd fd fa
=>0x0c0c7fff9b00: fa fa fa fa fd fd[fd]fd fd fd fd fa fa fa fa fa
  0x0c0c7fff9b10: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
  0x0c0c7fff9b20: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c0c7fff9b30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9b40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9b50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==30054==ABORTING
```

### PR DESCRIPTION
**Pull request by erenon**
Session stores shared_ptr of Channels,
shared with the respective SessionWriters.

The Channel is closed if only the Session owns it,
checked by shared_ptr::use_count.

Stability of Channel references is provided by the shared_ptr,
storing them in a list is no longer necessary -
it is replaced with a vector, that is faster to iterate.

Motivation: use-after-free if SessionWriter is destroyed
later than the Session it references. See contrived
test swap_writers_of_different_sessions that reproduces the issue.

Fixes #40

### CODE REVIEW

File: include/binlog/Session.hpp [hunk 1]
```diff
@@ -345,7 +347,8 @@ Session::ConsumeResult Session::consume(OutputStream& out)
     if (isClosed)
     {
       // queue is empty and closed, remove it
-      it = _channels.erase(it);
+      std::move(it+1, _channels.end(), it);
```
Comment (andrewkcorcoran) [inline include/binlog/Session.hpp]: Does the order of the vector matter? If not then you could swap the last element with the current and skip all the moves.

It also might be worth considering refactoring the loop to be separate erase and remove steps so removing all the elements are done in one go rather than one at a time?

Comment (erenon) [reply include/binlog/Session.hpp]: Order does not matter, but still wanted to keep the same behavior, to be less surprising in some cases. In the future, the vector might be replaced by a lockfree intrusive list (to save the lock in createChannel), that will have the same semantics.

Separate remove loop: not that trivial, as isClosed must be checked before the empty read, otherwise a race becomes possible:

 1. Consumer reads empty queue
 2. Producer adds data to the queue
 3. Producer closes the queue
 4. Consumer `std::remove_if`s closed queues - data added in step 2. is lost

To prevent this, the result of isClosed has to be stored in the first loop, not making the overall result much prettier.
